zuihou:
  database:
    isSeata: false
    tenantDatabasePrefix: zuihou_extend
  swagger:
    docket:
      demo:
        title: 演示服务
        base-package: com.github.zuihou.demo.controller

logging:
  io.seata: debug
  org.springframework.cloud.alibaba.seata.web: debug

server:
  servlet:
    context-path:
  port: 8770



spring:
  cloud:
    nacos:
      discovery:
        metadata:
          grayversion: demo
